"""
Markdown reporting helpers.

Every measured result in this project lands in docs/results.md.  Tasks run
independently and are re-run often, so sections are addressed by heading and
replaced in place rather than appended — otherwise re-running training would
stack duplicate, conflicting tables in the same file.
"""

from __future__ import annotations

import pathlib
from typing import Sequence

RESULTS_PATH = pathlib.Path(__file__).resolve().parent.parent / "docs" / "results.md"

_HEADER = """# Results

Measured outputs from the ML pipeline. Every table here is regenerated by a
script — do not edit by hand.
"""


def markdown_table(headers: Sequence[str], rows: Sequence[Sequence[object]]) -> str:
    """Render a GitHub-flavoured markdown table."""
    out = ["| " + " | ".join(str(h) for h in headers) + " |"]
    out.append("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


def upsert_section(heading: str, body: str, path: pathlib.Path = RESULTS_PATH) -> None:
    """
    Replace the `## heading` section with `body`, or append it if absent.

    A section runs from its own `## ` line up to the next `## ` line, so
    subsections nested under it are replaced along with it.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    text = path.read_text(encoding="utf-8") if path.exists() else _HEADER

    marker = f"## {heading}"
    section = f"{marker}\n\n{body.rstrip()}\n"

    lines = text.splitlines()
    start = next((i for i, line in enumerate(lines) if line.strip() == marker), None)

    if start is None:
        text = text.rstrip() + "\n\n" + section
    else:
        end = next(
            (i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")),
            len(lines),
        )
        text = "\n".join(lines[:start]) + "\n" + section
        if end < len(lines):
            text += "\n" + "\n".join(lines[end:])

    path.write_text(text.rstrip() + "\n", encoding="utf-8")
